mybatis:
  mapper-locations: classpath*:**/*Mapper.xml
  configuration:
    map-underscore-to-camel-case: true
spring:
  datasource:
    name: jiajiao
    url: jdbc:mysql://localhost:3306/jiajiao?serverTimezone=Asia/Shanghai&characterEncoding=UTF8
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
