mybatis:
  mapper-locations: classpath*:**/*Mapper.xml
spring:
  datasource:
    name: jiajiao
    url: jdbc:mysql://localhost:3306/jiajiao?serverTimezone=Asia/Shanghai
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
